### ISSUE TITLE
Fail finding the text box to send

### ISSUE THREAD

**Issue by DevDorrejo** [holps-7/WhatsApp-Bulk-Messaging-Bot#1]
![image](https://user-images.githubusercontent.com/7697566/89699679-7386f400-d8f6-11ea-8c77-d4874baced44.png)
i search the class name for the 2S1VP, but on my screen appear other name
![image](https://user-images.githubusercontent.com/7697566/89699724-bea10700-d8f6-11ea-9d0a-74529a869057.png)
whatsapp is changing the class name.

it go to the number and name of the contact (Nice better than anyone) but fail to find the text box

**Comment by holps-7** [comment]
Thanks for pointing it out, I'll update it soon.

**Comment by holps-7** [comment]
@DevDorrejo I think this issue #1 is solved. So I am closing this issue.

**Comment by DevDorrejo** [comment]
will test it them, thank you

**Comment by DevDorrejo** [comment]
work 1000% thank you, i will use this app because i am looking solution to bulk message whatsapp for schools to students/parents, it is possible to send multimedia/docs?

(All this installation will be free on schools on my country)

**Comment by holps-7** [comment]
Nice to hear that you find this repository useful... 🙂
Yes it is possible to send multimedia/docs, **I'll add the support to send multimedia and documents soon.**
And to answer your next query, **yes installing and using this repository will be free**.
