### ISSUE TITLE
Partner for the project (Share your contact)

### ISSUE THREAD

**Issue by ghost** [holps-7/WhatsApp-Bulk-Messaging-Bot#2]
Hi @holps-7 

Nice to meet you my name is Alfonso Hernandez 

We are interested in supporting and being allies of the project since it is great, very fast and efficient, to start small and consolidate a strong bot that can be integrated with multiple platforms (Telegram, Facebook) with a nice graphic interface. We could talk through Email or Telegram.

Thank you and we look forward to your prompt response.

A hug

**Comment by holps-7** [comment]
You can ping me at holps@protonmail.com
