### ISSUE TITLE
Format how the message is sended

### ISSUE THREAD

**Issue by DevDorrejo** [holps-7/WhatsApp-Bulk-Messaging-Bot#3]
Hello, i am back again, i need a little help with this:

i want to send this message
![image](https://user-images.githubusercontent.com/7697566/91731839-636cd800-eb75-11ea-89cb-d64dd31816aa.png)

but the bot is sending it this way:
![image](https://user-images.githubusercontent.com/7697566/91731933-86978780-eb75-11ea-889d-343d37d4a7fe.png)

Is there a way to send it like a whole message?

thank you.

**Comment by holps-7** [comment]
I have added the support for sending the multiple line messages.

Follow these steps to format the multiple line message:-

- Enclose the message within **""** in .csv file

- Insert the newline escape sequence **\n** wherever required to change the line, as it will create a new line for the forthcoming text.
<br>
If you want to send the following message:

![Screenshot 2020-09-03 at 11 44 22 AM](https://user-images.githubusercontent.com/43104299/92077839-d75bea00-edda-11ea-8f26-b7a04787c9f5.png)

Format the message in the .csv file as-
"IMDB Top 10 rated movies of all time\n1. The Shawshank Redemption (1994)\nR | 142 min | Drama | 9.3 | 80 Metascore\nTwo imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.\nDirector: Frank Darabont | Stars: Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler\nVotes: 2,278,599 | Gross: $28.34M\n2. The Godfather (1972)\nR | 175 min | Crime, Drama | 9.2 | 100 Metascore\nThe aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.\nDirector: Francis Ford Coppola | Stars: Marlon Brando, Al Pacino, James Caan, Diane Keaton\nVotes: 1,572,499 | Gross: $134.97M\n3. The Godfather: Part II (1974)\nR | 202 min | Crime, Drama | 9 | 90 Metascore\nThe early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.\nDirector: Francis Ford Coppola | Stars: Al Pacino, Robert De Niro, Robert Duvall, Diane Keaton\nVotes: 1,098,611 | Gross: $57.30M\n4. The Dark Knight (2008)\nPG-13 | 152 min | Action, Crime, Drama | 9 | 84 Metascore\nWhen the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.\nDirector: Christopher Nolan | Stars: Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine\nVotes: 2,241,209 | Gross: $534.86M\n5. 12 Angry Men (1957)\nApproved | 96 min | Crime, Drama | 8.9 | 96 Metascore\nA jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.\nDirector: Sidney Lumet | Stars: Henry Fonda, Lee J. Cobb, Martin Balsam, John Fiedler\nVotes: 668,417 | Gross: $4.36M\n6. Schindler's List (1993)\nR | 195 min | Biography, Drama, History | 8.9 | 94 Metascore\nIn German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.\nDirector: Steven Spielberg | Stars: Liam Neeson, Ralph Fiennes, Ben Kingsley, Caroline Goodall\nVotes: 1,183,133 | Gross: $96.90M\n7. The Lord of the Rings: The Return of the King (2003)\nPG-13 | 201 min | Action, Adventure, Drama | 8.9 | 94 Metascore\nGandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.\nDirector: Peter Jackson | Stars: Elijah Wood, Viggo Mortensen, Ian McKellen, Orlando Bloom\nVotes: 1,604,111 | Gross: $377.85M\n8. Pulp Fiction (1994)\nR | 154 min | Crime, Drama | 8.9 | 94 Metascore\nThe lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.\nDirector: Quentin Tarantino | Stars: John Travolta, Uma Thurman, Samuel L. Jackson, Bruce Willis\nVotes: 1,779,972 | Gross: $107.93M\n9. The Good, the Bad and the Ugly (1966)\nR | 178 min | Western | 8.8 | 90 Metascore\nA bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.\nDirector: Sergio Leone | Stars: Clint Eastwood, Eli Wallach, Lee Van Cleef, Aldo Giuffrè\nVotes: 672,439 | Gross: $6.10M\n10. Fight Club (1999)\nR | 139 min | Drama | 8.8 | 66 Metascore\nAn insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.\nDirector: David Fincher | Stars: Brad Pitt, Edward Norton, Meat Loaf, Zach Grenier\nVotes: 1,807,234 | Gross: $37.03M"

**Comment by DevDorrejo** [comment]
Thank you very much
